### ISSUE TITLE
fusuma does not run or show any error in Terminal

### ISSUE THREAD

**Issue by ruppalsingh** [iberianpig/fusuma#11]
After following the instructions, and running `fusuma`, I see nothing in the console. I waited for 5 minutes, but nothing.

Upon interrupting the process with `Ctrl+C`, I get the following:

```
/home/<username>/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fusuma-0.1.4/lib/fusuma.rb:19:in `each': Interrupt
from /home/<username>/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fusuma-0.1.4/lib/fusuma.rb:19:in `block in read_libinput'
from /home/<username>/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open3.rb:205:in `popen_run'
from /home/<username>/.rbenv/versions/2.3.0/lib/ruby/2.3.0/open3.rb:95:in `popen3'
from /home/<username>/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fusuma-0.1.4/lib/fusuma.rb:18:in `read_libinput'
from /home/<username>/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fusuma-0.1.4/lib/fusuma.rb:12:in `run'
from /home/<username>/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fusuma-0.1.4/exe/fusuma:5:in `<top (required)>'
from /home/<username>/.rbenv/versions/2.3.0/bin/fusuma:22:in `load'
from /home/<username>/.rbenv/versions/2.3.0/bin/fusuma:22:in `<main>'
```

Running Ruby 2.3.0 on elementaryOS Loki 0.4 x64.

**Comment by iberianpig** [comment]
I updated Fusuma for debug mode.
Please try `-v` option.
