### ISSUE TITLE
GemNotFoundException when running sudo fusuma

### ISSUE THREAD

**Issue by hurani** [iberianpig/fusuma#120]
Running `fusuma` returns the error:
`E, [2019-05-14T18:33:04.599911 #5762] ERROR -- : Touchpad is not found`

Running `sudo fusuma` returns the error:
Traceback (most recent call last):
	2: from /home/karim/.gem/ruby/2.6.0/bin/fusuma:23:in `<main>'
	1: from /usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem fusuma (>= 0.a) with executable fusuma (Gem::GemNotFoundException)

Any suggestions?

**Comment by hurani** [comment]
I found the solution, I had to add my user to the input group by running this command then rebooting:
`sudo gpasswd -a $USER input`
