### ISSUE TITLE
parse_finger_directions: undefined method `tr' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by peyloride** [iberianpig/fusuma#29]
Hello,

I'm trying to use fusuma on my Archlinux setup. I'm using latest packages and linux-zen kernel. Libinput-debug-events shows the gestures but fusuma throws error. My ruby version is 2.4.0

fusuma -v:
```
D, [2017-02-02T11:45:42.287273 #2946] DEBUG -- : Device:           Power Button

D, [2017-02-02T11:45:42.288038 #2946] DEBUG -- : Kernel:           /dev/input/event3

D, [2017-02-02T11:45:42.288700 #2946] DEBUG -- : Group:            1

D, [2017-02-02T11:45:42.289257 #2946] DEBUG -- : Seat:             seat0, default

D, [2017-02-02T11:45:42.289870 #2946] DEBUG -- : Capabilities:     keyboard 

D, [2017-02-02T11:45:42.290368 #2946] DEBUG -- : Tap-to-click:     n/a

D, [2017-02-02T11:45:42.290874 #2946] DEBUG -- : Tap-and-drag:     n/a

D, [2017-02-02T11:45:42.291352 #2946] DEBUG -- : Tap drag lock:    n/a

D, [2017-02-02T11:45:42.291838 #2946] DEBUG -- : Left-handed:      n/a

D, [2017-02-02T11:45:42.292327 #2946] DEBUG -- : Nat.scrolling:    n/a

D, [2017-02-02T11:45:42.293041 #2946] DEBUG -- : Middle emulation: n/a

D, [2017-02-02T11:45:42.293600 #2946] DEBUG -- : Calibration:      n/a

D, [2017-02-02T11:45:42.294095 #2946] DEBUG -- : Scroll methods:   none

D, [2017-02-02T11:45:42.294563 #2946] DEBUG -- : Click methods:    none

D, [2017-02-02T11:45:42.295036 #2946] DEBUG -- : Disable-w-typing: n/a

D, [2017-02-02T11:45:42.295509 #2946] DEBUG -- : Accel profiles:   n/a

D, [2017-02-02T11:45:42.295982 #2946] DEBUG -- : Rotation:         n/a

D, [2017-02-02T11:45:42.296519 #2946] DEBUG -- : 

D, [2017-02-02T11:45:42.297021 #2946] DEBUG -- : Device:           Video Bus

D, [2017-02-02T11:45:42.297506 #2946] DEBUG -- : Kernel:           /dev/input/event6

D, [2017-02-02T11:45:42.300149 #2946] DEBUG -- : Group:            2

D, [2017-02-02T11:45:42.300334 #2946] DEBUG -- : Seat:             seat0, default

D, [2017-02-02T11:45:42.300437 #2946] DEBUG -- : Capabilities:     keyboard 

D, [2017-02-02T11:45:42.300524 #2946] DEBUG -- : Tap-to-click:     n/a

D, [2017-02-02T11:45:42.300614 #2946] DEBUG -- : Tap-and-drag:     n/a

D, [2017-02-02T11:45:42.300694 #2946] DEBUG -- : Tap drag lock:    n/a

D, [2017-02-02T11:45:42.306339 #2946] DEBUG -- : Left-handed:      n/a

D, [2017-02-02T11:45:42.306855 #2946] DEBUG -- : Nat.scrolling:    n/a

D, [2017-02-02T11:45:42.307185 #2946] DEBUG -- : Middle emulation: n/a

D, [2017-02-02T11:45:42.307295 #2946] DEBUG -- : Calibration:      n/a

D, [2017-02-02T11:45:42.307384 #2946] DEBUG -- : Scroll methods:   none

D, [2017-02-02T11:45:42.307469 #2946] DEBUG -- : Click methods:    none

D, [2017-02-02T11:45:42.308602 #2946] DEBUG -- : Disable-w-typing: n/a

D, [2017-02-02T11:45:42.308793 #2946] DEBUG -- : Accel profiles:   n/a

D, [2017-02-02T11:45:42.308872 #2946] DEBUG -- : Rotation:         n/a

D, [2017-02-02T11:45:42.308947 #2946] DEBUG -- : 

D, [2017-02-02T11:45:42.309025 #2946] DEBUG -- : Device:           Sleep Button

D, [2017-02-02T11:45:42.309099 #2946] DEBUG -- : Kernel:           /dev/input/event2

D, [2017-02-02T11:45:42.309199 #2946] DEBUG -- : Group:            3

D, [2017-02-02T11:45:42.309277 #2946] DEBUG -- : Seat:             seat0, default

D, [2017-02-02T11:45:42.309353 #2946] DEBUG -- : Capabilities:     keyboard 

D, [2017-02-02T11:45:42.309426 #2946] DEBUG -- : Tap-to-click:     n/a

D, [2017-02-02T11:45:42.309553 #2946] DEBUG -- : Tap-and-drag:     n/a

D, [2017-02-02T11:45:42.309631 #2946] DEBUG -- : Tap drag lock:    n/a

D, [2017-02-02T11:45:42.309705 #2946] DEBUG -- : Left-handed:      n/a

D, [2017-02-02T11:45:42.309779 #2946] DEBUG -- : Nat.scrolling:    n/a

D, [2017-02-02T11:45:42.309854 #2946] DEBUG -- : Middle emulation: n/a

D, [2017-02-02T11:45:42.309927 #2946] DEBUG -- : Calibration:      n/a

D, [2017-02-02T11:45:42.309999 #2946] DEBUG -- : Scroll methods:   none

D, [2017-02-02T11:45:42.310075 #2946] DEBUG -- : Click methods:    none

D, [2017-02-02T11:45:42.310149 #2946] DEBUG -- : Disable-w-typing: n/a

D, [2017-02-02T11:45:42.310222 #2946] DEBUG -- : Accel profiles:   n/a

D, [2017-02-02T11:45:42.310290 #2946] DEBUG -- : Rotation:         n/a

D, [2017-02-02T11:45:42.310357 #2946] DEBUG -- : 

D, [2017-02-02T11:45:42.310427 #2946] DEBUG -- : Device:           VGA Webcam

D, [2017-02-02T11:45:42.310496 #2946] DEBUG -- : Kernel:           /dev/input/event12

D, [2017-02-02T11:45:42.310582 #2946] DEBUG -- : Group:            4

D, [2017-02-02T11:45:42.310653 #2946] DEBUG -- : Seat:             seat0, default

D, [2017-02-02T11:45:42.310721 #2946] DEBUG -- : Capabilities:     keyboard 

D, [2017-02-02T11:45:42.310789 #2946] DEBUG -- : Tap-to-click:     n/a

D, [2017-02-02T11:45:42.310867 #2946] DEBUG -- : Tap-and-drag:     n/a

D, [2017-02-02T11:45:42.310939 #2946] DEBUG -- : Tap drag lock:    n/a

D, [2017-02-02T11:45:42.311028 #2946] DEBUG -- : Left-handed:      n/a

D, [2017-02-02T11:45:42.311100 #2946] DEBUG -- : Nat.scrolling:    n/a

D, [2017-02-02T11:45:42.311171 #2946] DEBUG -- : Middle emulation: n/a

D, [2017-02-02T11:45:42.311243 #2946] DEBUG -- : Calibration:      n/a

D, [2017-02-02T11:45:42.311316 #2946] DEBUG -- : Scroll methods:   none

D, [2017-02-02T11:45:42.311388 #2946] DEBUG -- : Click methods:    none

D, [2017-02-02T11:45:42.311460 #2946] DEBUG -- : Disable-w-typing: n/a

D, [2017-02-02T11:45:42.311535 #2946] DEBUG -- : Accel profiles:   n/a

D, [2017-02-02T11:45:42.311608 #2946] DEBUG -- : Rotation:         n/a

D, [2017-02-02T11:45:42.311679 #2946] DEBUG -- : 

D, [2017-02-02T11:45:42.311752 #2946] DEBUG -- : Device:           ELAN0501:00 04F3:3010 Touchpad

D, [2017-02-02T11:45:42.311824 #2946] DEBUG -- : Kernel:           /dev/input/event5

D, [2017-02-02T11:45:42.311905 #2946] DEBUG -- : Group:            5

D, [2017-02-02T11:45:42.311977 #2946] DEBUG -- : Seat:             seat0, default

D, [2017-02-02T11:45:42.312050 #2946] DEBUG -- : Size:             100.41x56.06mm

D, [2017-02-02T11:45:42.312121 #2946] DEBUG -- : Capabilities:     pointer 

D, [2017-02-02T11:45:42.312193 #2946] DEBUG -- : Tap-to-click:     disabled

D, [2017-02-02T11:45:42.312271 #2946] DEBUG -- : Tap-and-drag:     enabled

D, [2017-02-02T11:45:42.312343 #2946] DEBUG -- : Tap drag lock:    disabled

D, [2017-02-02T11:45:42.312414 #2946] DEBUG -- : Left-handed:      disabled

D, [2017-02-02T11:45:42.312486 #2946] DEBUG -- : Nat.scrolling:    disabled

D, [2017-02-02T11:45:42.312559 #2946] DEBUG -- : Middle emulation: disabled

D, [2017-02-02T11:45:42.312631 #2946] DEBUG -- : Calibration:      n/a

D, [2017-02-02T11:45:42.312711 #2946] DEBUG -- : Scroll methods:   *two-finger edge 

D, [2017-02-02T11:45:42.312805 #2946] DEBUG -- : Click methods:    *button-areas clickfinger 

D, [2017-02-02T11:45:42.312878 #2946] DEBUG -- : Disable-w-typing: enabled

D, [2017-02-02T11:45:42.312946 #2946] DEBUG -- : Accel profiles:   none

D, [2017-02-02T11:45:42.313997 #2946] DEBUG -- : Rotation:         n/a

D, [2017-02-02T11:45:42.314117 #2946] DEBUG -- : 

D, [2017-02-02T11:45:42.314186 #2946] DEBUG -- : Device:           AT Translated Set 2 keyboard

D, [2017-02-02T11:45:42.314260 #2946] DEBUG -- : Kernel:           /dev/input/event0

D, [2017-02-02T11:45:42.314366 #2946] DEBUG -- : Group:            6

D, [2017-02-02T11:45:42.314441 #2946] DEBUG -- : Seat:             seat0, default

D, [2017-02-02T11:45:42.314520 #2946] DEBUG -- : Capabilities:     keyboard 

D, [2017-02-02T11:45:42.314591 #2946] DEBUG -- : Tap-to-click:     n/a

D, [2017-02-02T11:45:42.314664 #2946] DEBUG -- : Tap-and-drag:     n/a

D, [2017-02-02T11:45:42.314734 #2946] DEBUG -- : Tap drag lock:    n/a

D, [2017-02-02T11:45:42.314805 #2946] DEBUG -- : Left-handed:      n/a

D, [2017-02-02T11:45:42.314877 #2946] DEBUG -- : Nat.scrolling:    n/a

D, [2017-02-02T11:45:42.314952 #2946] DEBUG -- : Middle emulation: n/a

D, [2017-02-02T11:45:42.315021 #2946] DEBUG -- : Calibration:      n/a

D, [2017-02-02T11:45:42.315091 #2946] DEBUG -- : Scroll methods:   none

D, [2017-02-02T11:45:42.315163 #2946] DEBUG -- : Click methods:    none

D, [2017-02-02T11:45:42.315234 #2946] DEBUG -- : Disable-w-typing: n/a

D, [2017-02-02T11:45:42.315321 #2946] DEBUG -- : Accel profiles:   n/a

D, [2017-02-02T11:45:42.315395 #2946] DEBUG -- : Rotation:         n/a

D, [2017-02-02T11:45:42.315468 #2946] DEBUG -- : 

D, [2017-02-02T11:45:42.315542 #2946] DEBUG -- : Device:           Acer WMI hotkeys

D, [2017-02-02T11:45:42.315616 #2946] DEBUG -- : Kernel:           /dev/input/event7

D, [2017-02-02T11:45:42.315706 #2946] DEBUG -- : Group:            7

D, [2017-02-02T11:45:42.315780 #2946] DEBUG -- : Seat:             seat0, default

D, [2017-02-02T11:45:42.315853 #2946] DEBUG -- : Capabilities:     keyboard 

D, [2017-02-02T11:45:42.315924 #2946] DEBUG -- : Tap-to-click:     n/a

D, [2017-02-02T11:45:42.316000 #2946] DEBUG -- : Tap-and-drag:     n/a

D, [2017-02-02T11:45:42.316071 #2946] DEBUG -- : Tap drag lock:    n/a

D, [2017-02-02T11:45:42.316193 #2946] DEBUG -- : Left-handed:      n/a

D, [2017-02-02T11:45:42.316265 #2946] DEBUG -- : Nat.scrolling:    n/a

D, [2017-02-02T11:45:42.316336 #2946] DEBUG -- : Middle emulation: n/a

D, [2017-02-02T11:45:42.316406 #2946] DEBUG -- : Calibration:      n/a

D, [2017-02-02T11:45:42.316476 #2946] DEBUG -- : Scroll methods:   none

D, [2017-02-02T11:45:42.316546 #2946] DEBUG -- : Click methods:    none

D, [2017-02-02T11:45:42.316617 #2946] DEBUG -- : Disable-w-typing: n/a

D, [2017-02-02T11:45:42.316688 #2946] DEBUG -- : Accel profiles:   n/a

D, [2017-02-02T11:45:42.316759 #2946] DEBUG -- : Rotation:         n/a

D, [2017-02-02T11:45:42.316829 #2946] DEBUG -- : 

D, [2017-02-02T11:45:42.316975 #2946] DEBUG -- : {:libinput_command=>"stdbuf -oL -- libinput-debug-events --enable-dwt --device /dev/input/event5"}
```

when i do 3 finger gestures it throws the following error message;

```
/home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/lib/fusuma/gesture_action.rb:46:in `parse_finger_directions': undefined method `tr' for nil:NilClass (NoMethodError)
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/lib/fusuma/gesture_action.rb:33:in `gesture_action_arguments'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/lib/fusuma/gesture_action.rb:22:in `initialize_by'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/lib/fusuma.rb:38:in `block (2 levels) in read_libinput'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/lib/fusuma.rb:37:in `each'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/lib/fusuma.rb:37:in `block in read_libinput'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/2.4.0/open3.rb:205:in `popen_run'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/2.4.0/open3.rb:95:in `popen3'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/lib/fusuma.rb:36:in `read_libinput'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/lib/fusuma.rb:21:in `run'
	from /home/peyloride/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fusuma-0.2.6/exe/fusuma:21:in `<top (required)>'
	from /home/peyloride/.rbenv/versions/2.4.0/bin/fusuma:22:in `load'
	from /home/peyloride/.rbenv/versions/2.4.0/bin/fusuma:22:in `<main>'

```

**Comment by tobac** [comment]
This has already been reported as issue #26

**Comment by peyloride** [comment]
Sorry, you are right. I saw that post but i just think similiar issue, not the same.

**Comment by iberianpig** [comment]
@peyloride please update fusuma, and please confirm fix your problem.

**Comment by iberianpig** [comment]
If you still have problems, please reopen this ticket.
