### ISSUE TITLE
fusuma doesn't work on wayland

### ISSUE THREAD

**Issue by TroyMitchell911** [iberianpig/fusuma#323]
I switch from `x11` to `wayland` and I went this trouble:

```bash
/var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/gnome.rb:111:in `gnome_shell_eval': unhandled exception
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/gnome.rb:75:in `active_application'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/gnome.rb:117:in `block in on_active_application_changed'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/gnome.rb:115:in `loop'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/gnome.rb:115:in `on_active_application_changed'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/gnome.rb:36:in `register_on_application_changed'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/gnome.rb:27:in `block in watch_start'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/user_switcher.rb:28:in `block in as_user'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma/custom_process.rb:18:in `block in fork'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma/custom_process.rb:15:in `fork'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma/custom_process.rb:15:in `fork'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/user_switcher.rb:26:in `as_user'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/appmatcher/gnome.rb:24:in `watch_start'
	from /var/lib/gems/3.0.0/gems/fusuma-plugin-appmatcher-0.7.1/lib/fusuma/plugin/inputs/appmatcher_input.rb:16:in `io'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma/plugin/inputs/input.rb:23:in `map'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma/plugin/inputs/input.rb:23:in `select'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma.rb:102:in `input'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma.rb:78:in `pipeline'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma.rb:74:in `block in run'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma.rb:74:in `loop'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma.rb:74:in `run'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/lib/fusuma.rb:21:in `run'
	from /var/lib/gems/3.0.0/gems/fusuma-3.5.0/exe/fusuma:50:in `<top (required)>'
	from /usr/local/bin/fusuma:25:in `load'
	from /usr/local/bin/fusuma:25:in `<main>'
E, [2024-11-09T16:52:10.424869 #16223] ERROR -- : Fusuma::Plugin::Inputs::AppmatcherInput: end of file reached
E, [2024-11-09T16:52:10.424923 #16223] ERROR -- : Shutdown fusuma process...

```

**Comment by iberianpig** [comment]
Did you installed gnome-extension if you using Gnome Wayland?

https://github.com/iberianpig/fusuma-plugin-appmatcher?tab=readme-ov-file#install-appmatcher-gnome-shell-extensions-on-wayland
