### ISSUE TITLE
when I run the fusuma  ,i met a problem ,it seems that some wrong between the code 

### ISSUE THREAD

**Issue by liuliu7616** [iberianpig/fusuma#40]
/usr/lib/ruby/2.3.0/open3.rb:208:in `join': Interrupt
	from /usr/lib/ruby/2.3.0/open3.rb:208:in `popen_run'
	from /usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:36:in `read_libinput'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/lib/fusuma.rb:21:in `run'
	from /var/lib/gems/2.3.0/gems/fusuma-0.3.3/exe/fusuma:21:in `<top (required)>'
	from /usr/local/bin/fusuma:23:in `load'
	from /usr/local/bin/fusuma:23:in `<main>'

**Comment by liuliu7616** [comment]
I used the ubuntu kylin 16.04os   when i start the fusuma ,it just stay at here  seems like lock   and util i press ctrl +c  ,it will print the errors
